# Colon_Cancer_P2 data/Colon_Cancer_P2 8
# Colon_Normal_P3 data/Colon_Normal_P3 8
#colon_cancer_P1 data/colon_cancer_P1
#colon_normal_P5 data/colon_normal_P5
#Kidney_Cancer_data data/Kidney_Cancer_data
#Kidney_Normal_data data/Kidney_Normal_data
import pandas as pd
import os
import sys
import json
import glob
import warnings
warnings.filterwarnings("ignore")
import logging
L = logging.getLogger("spatialsnake_user")
L.setLevel(logging.INFO)
L.propagate = False
log_handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('%(asctime)s: %(levelname)s - %(message)s')
log_handler.setFormatter(formatter)
if not L.handlers:
    L.addHandler(log_handler)
include: "function/get_sample.smk"

# if config.get("load_config")==False:
#   configfile: "config.yaml"

annotion_list = config.get("annotion_list", "annotion.txt")
filter_list = config.get("filter_list", False)
sample_list = config.get("sample_list", "sample.txt")

spatialsnake_path = config.get("spatialsnake_path", "")
results_folder = config.get("results_folder", "results")

option = config.get("option","integrate")

channel = config.get("channel", "single_analysis")

data_fold = config.get("data_fold", "data")
run_type = config.get("run_type", "visium")
#################  xenium ###########
cells_boundaries = config.get("cells_boundaries", False)
nucleus_boundaries = config.get("nucleus_boundaries", False)
nucleus_labels = config.get("nucleus_labels", False)
morphology_mip = config.get("morphology_mip", False)

markers_algorithm = config.get("markers_algorithm", "wilcoxon")
image_slice = config.get("image_slice", False)

if image_slice == "True":
    coord = []
    x1 = config.get("x1")
    x2 = config.get("x2")
    y1 = config.get("y1")
    y2 = config.get("y2")
    coord.append(x1)
    coord.append(x2)
    coord.append(y1)
    coord.append(y2)
tsene = config.get("tsene", False)
MIN_DIST = config.get("MIN_DIST", 0.3)
SPREAD = config.get("SPREAD", 1)
variable = config.get("variable", False)
NEIGHBORS = config.get("NEIGHBORS", 10)
pcs = config.get("pcs",30)


RES = config.get("resolution", 0.5)
n_top_genes = config.get("n_top_genes", 1000)
batch_method = config.get("batch_method", None)
n_comps = config.get("n_comps", 50)

if channel == "single_analysis" and batch_method!=None:
    L.info("your argument harmony just allowed setting in compare_analysis channal")
    batch_method = None

spacies = config.get("human", "human")
cluster_algorithm = config.get("cluster_algorithm", "leiden")
anno_algorithm = config.get("anno_algorithm", "mannul")
compare_algorithm = config.get("compare_algorithm", "DEseq2")
cell_focus = config.get("cell_focus", "Colorectal")
device = config.get("device", "cpu")
runpipe = config.get("runpipe", "pysenic")
counts_data = config.get("counts_data", "hgnc_symbol")
iterations = config.get("iterations", 500)
threshold = config.get("threshold", 0.1)
threads = config.get("threads", 32)
pvalue = config.get("pvalue", 0.05)
sample_id = config.get("sample_type", "Normal")
n_clusters = config.get("n_clusters", 10)
output_name = config.get("output_name", "Normal")
mt_threshold = config.get("mt_threshold", 50.0)

geojson = "cell_segmentations.geojson"
image = "tissue_hires_image.png"
scale_factors = "scalefactors_json.json"
coor_file = "BeadLocationsForR.csv"

k_geom =config.get("k_geom")
max_m = config.get("max_m")
nbr_weight_decay = config.get("nbr_weight_decay")
pca_dims = config.get("pca_dims")
lambda_list = config.get("lambda_list")

## downsample for spatialdata
sketch = config.get("sketch",False)
sample_rate = config.get("sample_rate",1.0)

INPUT_FIlE=config.get("INPUT_FIlE")
barcode=config.get('clusters')
max_x=config.get('max_x')
min_x=config.get("min_x")
max_y=config.get("max_y")
min_y=config.get("min_y")

if type != "xenium":
    image_type = config.get("image_type", "hires")
    shape_type = config.get("shape_type", "cell_boundaries")
else:
    image_type = config.get("image_type", "morphology_focus")
    shape_type = config.get("shape_type", "cell_circle")



if os.path.exists(sample_list) == True:
    main_file = []
    samples = []
    bin_size = []
    group = []
    if channel == 'single_analysis':
        if run_type == "visium" or run_type == "xenium" or run_type == "visium_segment" or run_type == "slide_seq":
            samples, main_file = get_sample_paths(sample_list)
        elif run_type == "visium_HD":
            samples, main_file, bin_size = get_sample_paths(sample_list)
    else:
        if run_type == "visium" or run_type == "xenium" or run_type == "visium_segment" or run_type == "slide_seq":
            samples, main_file, group = get_sample_paths(sample_list)
        elif run_type == "visium_HD":
            samples, main_file, bin_size, group = get_sample_paths(sample_list)
    main_file = main_file[0]
def parameter_output(samples, option):
    outs = []
    if option == 'integrate':
        if channel == 'single_analysis':
            if run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
                outs += expand(os.path.join(results_folder, "{sample}",'integrate',"{sample}.zarr"), sample=samples)
            if run_type == "visium_HD":
                outs += expand(os.path.join(results_folder, "{sample}_{bin}um", 'integrate',"{sample}.zarr"), zip, sample=samples, bin=bin_size)
            if run_type == "slide_seq":
                outs += expand(os.path.join(results_folder, "{sample}",'integrate',"{sample}.h5ad"), sample=samples)
        if channel == "compare_analysis" and flag == 'merge':
            if run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
                outs += expand(os.path.join(results_folder, "{group}", "{sample}.zarr"), zip, sample=samples, group=group)
            if run_type == "visium_HD":
                outs += expand(os.path.join(results_folder, "{group}_{bin}um", "{sample}.zarr"), zip, sample=samples, bin=bin_size, group=group)
            if run_type == "slide_seq":
                outs += expand(os.path.join(results_folder, "{group}", "{sample}.h5ad"), zip, sample=samples, group=group)
        if channel == "compare_analysis" and flag == 'ALL':  
            outs.append(os.path.join(results_folder, "merge_data","integrate","concatenated_sdata"))
        return outs
    if option == "preprocess":
        if channel == 'single_analysis':
            if run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
                outs += expand(os.path.join(results_folder, "{sample}", 'preprocess', "filter_{sample}.zarr"), sample=samples)
            if run_type == "visium_HD":
                outs += expand(os.path.join(results_folder, "{sample}_{bin}um", 'preprocess', "filter_{sample}.zarr"), zip, sample=samples, bin=bin_size)
            if run_type == "slide_seq":
                outs += expand(os.path.join(results_folder, "{sample}", 'preprocess', "filter_{sample}.h5ad"), sample=samples)
        if channel == "compare_analysis":
            outs.append(os.path.join(results_folder, "merge_data", 'preprocess', "filter_concatenated_sdata"))
        return outs
    if option == "annotion_help":
        if channel == 'single_analysis':
          if run_type == "visium_HD":
            return(expand(os.path.join(results_folder, "{sample}_{bin}um", 'clustering', 'kegg_data.csv'), zip, sample=samples, bin=bin_size))
          else:
            return(expand(os.path.join(results_folder, "{sample}", 'clustering', 'kegg_data.csv'), sample=samples))
        if channel == 'compare_analysis':
            return(os.path.join(results_folder, "merge_data", 'clustering', 'kegg_data.csv'))
    if option == "annotion" or option == "clustering":
        if channel == 'single_analysis':
            if run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
                outs += expand(os.path.join(results_folder, "{sample}", option, "{sample}.zarr"), sample=samples)
            if run_type == "visium_HD":
                outs += expand(os.path.join(results_folder, "{sample}_{bin}um", option, "{sample}.zarr"), zip, sample=samples, bin=bin_size)
            if run_type == "slide_seq":
                outs += expand(os.path.join(results_folder, "{sample}", option, "{sample}.h5ad"), sample=samples)
        if channel == "compare_analysis":
            outs.append(os.path.join(results_folder, "merge_data", option, "concatenated_sdata"))
        return outs
    if option == "compare_analyze":
        return(os.path.join(results_folder, "merge_data", 'compare_analysis', 'positive', 'kegg_data.csv'))
    if option == "advance_analysis":
        if runpipe == "cellPhoneDB":
            if channel == 'single_analysis':
                outs += expand(os.path.join(results_folder, "{sample}", runpipe, "{sample}_heatmap.png"), sample=samples)
            if channel == "compare_analysis":
                outs.append(os.path.join(results_folder, "merge_data", runpipe, "concentrate_heatmap.png"))
        if runpipe == "pysenic":
            outs.append(os.path.join(results_folder, "pysenic_results", f"{sample_id}.aucell.loom"))
        return outs
    if channel == "useful_tool":
        if option=="splitting":
           outs.append()

def input_file(run_type):
    if run_type == "visium" or run_type == "xenium" or run_type == "slide_seq":
        return(os.path.join(data_fold, '{sample}', main_file))
    elif run_type == "visium_HD":
        return(os.path.join(data_fold, '{sample}', "binned_outputs", "square_{bin}um", main_file))
    elif run_type == "visium_segment":
        return os.path.join(data_fold, "{sample}", "segmented_outputs", main_file)

def get_output(run_type):
    if channel == 'single_analysis':
        if run_type == "visium_HD":
            return(directory(os.path.join(results_folder, "{sample}_{bin}um", "{sample}.zarr")))
        elif run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
            return(directory(os.path.join(results_folder, "{sample}", "{sample}.zarr")))
        elif run_type == "slide_seq":
            return(os.path.join(results_folder, "{sample}", "{sample}.h5ad"))
    elif channel == "compare_analysis":
        if run_type == "visium_HD":
            return(directory(os.path.join(results_folder, "{group}_{bin}um", "{sample}.zarr")))
        elif run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
            return(directory(os.path.join(results_folder, "{group}", "{sample}.zarr")))
        elif run_type == "slide_seq":
            return(os.path.join(results_folder, "{group}", "{sample}.h5ad"))  

def nomal_file(run_type, segs):
    if channel == 'single_analysis':
        if run_type == "visium_HD":
            return((os.path.join(results_folder, "{sample}_{bin}um", segs, "{sample}.zarr")))
        elif run_type == "visium" or run_type == "xenium" or run_type == "visium_segment":
            return(os.path.join(results_folder, "{sample}", segs, "{sample}.zarr"))
        elif run_type == "slide_seq":
            return(os.path.join(results_folder, "{sample}", segs, "{sample}.h5ad"))
    if channel == "compare_analysis":
        return((parameter_output(samples, segs)))

def check_cell2Location_file(samples, run_type, input_singlecell, input_spatial, channel):
    if input_spatial == "" and not os.path.isdir(nomal_file(run_type, "")):
        sys.exit("please provide your st_file path or you can load in the zarr data with [spatialsnake integrate] which save in [results/]")
        L.info("please promiss your st_file haven't been normalization Log transformation Variance stabilizing transformation  PCA、t-SNE or UMAP....")
    if input_singlecell == "":
        L.info("please promiss your sc data has been anno")
        sys.exit("please provide your st_file path or you can download h5ad in your own path")
    if len(samples) > 1:
        sys.exit("Deconvolution annotation is very memory-intensive, so please process the samples one by one.")
    if os.path.splitext(input_spatial)[1][1:] == "zarr" and channel == "single_analysis":
        if os.path.isdir(f"data/{samples[0]}"):
            return(input_file(run_type))
        else:
            return("")
    else:
        L.info("please load in the zarr data which will save in [results/name.zarr] with [spatialsnake integrate] command")
        sys.exit()


if not filter_list:
    min_genes = config.get('min_counts', 3)
    min_cells = config.get('min_cells', 3)
else:
    L.info("!!!!! you are filter the sample by different params in filter_list.txt")
    filter_dict = seg_filter_sample(filter_list)
flag = 'ALL'
rule all:
    input:
        parameter_output(samples, option)

if option == "integrate":
    include: "rules/integrate.smk"
    if channel == "compare_analysis":
        flag = 'merge'
        include: "rules/merge.smk"
elif option == "preprocess":
    include: "rules/preprocess.smk"
elif option == "clustering":
    include: "rules/cluster.smk"
elif option == "annotion_help":
    include: "rules/annotion_help.smk"
elif option == "annotion":
    if anno_algorithm == "cell2Location":
        input_spatial = config.get("input_spatial", "") if config.get("input_spatial", "") != "" else nomal_file(run_type, "")
        input_singlecell = config.get("input_singlecell", "")
        input_st = check_cell2Location_file(samples, run_type, input_singlecell, input_spatial, channel)
        include: "rules/cell2Location_run.smk"
    elif anno_algorithm == "mannul":
        anno_data = get_annotion(annotion_list, samples)
        include: "rules/mannul.smk"
    elif anno_algorithm == "RCTD":
        include: "rules/RCTD.smk"
elif option == "compare_analyze":
    include: "rules/compare_analyze.smk"
elif option == "advance_analysis":
    if runpipe == "cellPhoneDB":
        include: "rules/cellPhoneDB.smk"
    elif runpipe == "pysenic":
        include: "rules/py_senic.smk"
    elif runpipe == "liana":
        include: "rules/run_liana.smk"
    elif runpipe == "cellcharter":
        include: "rules/run_cellcharter.smk"
elif option == "all":
    include: "rules/integrate.smk"
    if channel == "compare_analysis":
        flag = 'merge'
        include: "rules/merge.smk"
    include: "rules/preprocess.smk"
    include: "rules/cluster.smk"
    include: "rules/annotion_help.smk"
elif channel=="useful_tool":
    if option =="slice":
      include: "rule/run_slice.smk"
    
    
    
    
    
    
