[build-system]
requires = ["setuptools>=80.9.0,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spatialsnake"
dynamic = ["version", "dependencies", "optional-dependencies"]
authors = [
  { name = "lzh", email = "l-zh007@users.noreply.github.com" },
]
description = "A Python package for spatial transcriptomics analysis workflows."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["spatial transcriptomics", "bioinformatics", "snakemake", "spatialdata"]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.urls]
Homepage = "https://github.com/l-zh007/spatialsnake"
Issues = "https://github.com/l-zh007/spatialsnake/issues"

[project.scripts]
spatialsnake = "spatialsnake.command_line:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["spatialsnake*"]

[tool.setuptools.dynamic]
version = { attr = "spatialsnake.command_line.__version__" }
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.dynamic.optional-dependencies]
extended = { file = ["requirements-extended.txt"] }
