**

!setup.py
!MANIFEST.in
!README.md
!requirements.txt
!requirements-extended.txt

!spatialsnake/
!spatialsnake/**

!docker/
!docker/test3/
!docker/test3/locks/
!docker/test3/locks/**
!docker/test3/smoke_test.py
!docker/test3/conda_pack_compat.py
!docker/test3/artifacts/
!docker/test3/artifacts/test3-linux-64.tar.gz

**/__pycache__/
**/*.py[cod]
**/.DS_Store
